# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='users',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_books',
            field=models.ManyToManyField(related_name='users', to='likes_app.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='likes_app.User'),
        ),
    ]
